./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5277 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P282
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2101 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P657
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1883 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1263
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3394 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1667
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2488 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P2581
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3165 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P119
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P6056 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P960
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1367 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3956
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3360 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4927
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2871 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P645
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3497 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3639 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P2163
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1802 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2006
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2016 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5357
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P402 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P776
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3185 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P158
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P381 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1585 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3417
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1030 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P380
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P351 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1651
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3225 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P841
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1581 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P991
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3880 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1533
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4129 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1325
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P57 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P691
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P709 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P227
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5680 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P2163
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2659 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P227
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3780 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1014
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2364 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P162
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P644 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3329
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2980 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1296
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5951 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1986
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P828 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1667
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1799 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1936
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P647 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2728
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5081 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1343
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P427 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5945
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P486 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2213
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4490 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2772
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2188 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1038
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2581 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2267
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5391 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3018
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4141 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1366
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5607 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2750 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P51
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/ontology-beta#novalue /data/graphs/wikidata/sorted/rels/bfs-sorted/ontology-beta#directClaim
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3957 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4198
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P461 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155
./t2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1764 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P708
