./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P485 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1449
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1080 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1256
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3473
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4195 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P360
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P16 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P36
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P559 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2130
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1412 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3219
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2548 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5277 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3417
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P86 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2886
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P175 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2581
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P30 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1465
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P647 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1753 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P149
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P282 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3916
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P196 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1014
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P6 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2522
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3578 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P486
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1038 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5284
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P853 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2354
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1302 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P782
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P176 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2174
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4608 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2722
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P39 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P998
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P556 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3219
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4952 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P123
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2517 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P826 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P461
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1875 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P488
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P974 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5383
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P376 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P948
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3780 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1036
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P483 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1424
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P553 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P170
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2408 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4223
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P179 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1376
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P841 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2184
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P741 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P487
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1066 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4042
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P282 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P2581
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1427 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4431
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P674 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P241
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5105 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2354
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5277 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4614 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3643
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1884 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1843
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P509 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1375
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5130 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P463
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3578 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5166
./p2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2388 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1269
