./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P552 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P461 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P741
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P479 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1269
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P87 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P136 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P826
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5841 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P141
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P375 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P495 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P137
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1343 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P767 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3373
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P26 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1801 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1442
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2747 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1366 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2363
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3858 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1424
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P647 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P276 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P20
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1073 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1365 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1072
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P941 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P103 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1412
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P741 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2283 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2545
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P749 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P488 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2388
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1313 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1001 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1366
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1753 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1754 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P485 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P488 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P26
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1302 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P47 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P276
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P552 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P461 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P741
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P40 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P39 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P166
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1753 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P136 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P176 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1365 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P178
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2747 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1366 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2363
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1811 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1754 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P26 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P22 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3342
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P185 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3373 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P40
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P937 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P473 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4169
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4614 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P206 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P200
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P466 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1532 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P127
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1080 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P178 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P170
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1791 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4224 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1365 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P463
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1037 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P708 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P460
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1445 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P272 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P170
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P306 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P460 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P400
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P272 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P740 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P915
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1659 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P126 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1629
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P530 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P172 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P248 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P276 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P611
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P355 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1056 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P452
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1196 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2283 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P509
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2302 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1629
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P88 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P127 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P272
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P690 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P556 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1056 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1972 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2037
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3858 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1424
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P126 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P610 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P559
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3092 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P737 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1431
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3092 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3342 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P58
./tr2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1026 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1416 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P69
