./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1598 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P39 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1308
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1365 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1269 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P282
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1343 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P629 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P495
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1424 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1424 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2354 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P360
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P166 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1365 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1346
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P108 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P170 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3373
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P237 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1001 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2743 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4195 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1753 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P108
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P282 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1269
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P159 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1716 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P169 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P108
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P629 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P747
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P287 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1056
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P469 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4614 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P206
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3780 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P176 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1056
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P417 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P20
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1659 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1269 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1963
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2302 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1687
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3780 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P176 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1056
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1434 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P179
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1659 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P137 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1687
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P360 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2354
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3858 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1423
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1382 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1366
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1151 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2354 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P360
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4320 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1344 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1056 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1535 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P178
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P170 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3373 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P800
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P69 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1441 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P674
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2388 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1366 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1416
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2936 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1365
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P417 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P119 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P36
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4224 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1424 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P360 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2389 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2388
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3876 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1754 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1753
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4195 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P972 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P282 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P287 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1412
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P397 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1441 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P840
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P282 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P287 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1412
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4792 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P200 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P469
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1365 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P206 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P205
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P937 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1376 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P194
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P664 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P488 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P800
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4195 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P972 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P30 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P206 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P974
./tr1 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P398 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P196 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P397
