./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P485 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4195 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1753 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1424 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P264 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P750 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P541 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P360 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3222 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1313 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1269 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3137 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P206 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P205 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1434 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P400 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P437 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2417 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P108 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2397 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P102 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1071 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1116 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4908 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1811 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P360 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3096 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1687 /data/graphs/wikidata/sorted/rels/bfs-sorted/ontology-beta#propertyType 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2359 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P282 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P935 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5138 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P582 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1423 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P263 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1329 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2354 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P511 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P305 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P404 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1753 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1687 /data/graphs/wikidata/sorted/rels/bfs-sorted/ontology-beta#novalue 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2417 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1365 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P576 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1533 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P127 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P450 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1269 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P2581 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1343 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P629 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P580 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3096 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1687 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1855 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1990 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P427 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P508 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5280 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P487 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3092 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P25 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1266 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P410 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P366 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1225 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4195 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4224 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1417 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4552 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2614 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P585 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P81 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P137 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2013 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P411 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P123 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3035 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P803 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P140 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P244 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P609 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2184 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P244 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2515 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P803 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P349 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3095 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P425 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2545 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1535 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2283 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4224 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P915 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3417 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2377 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P275 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P856 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1142 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P140 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3219 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3306 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1414 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P287 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P864 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P828 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2959 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P2581 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P611 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2283 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1535 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P306 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2184 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P856 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P658 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P483 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P649 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P129 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1687 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2302 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P532 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1343 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P793 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P20 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P931 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2003 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P136 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2283 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P652 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1687 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1552 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3827 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2684 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 
./p3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1792 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1753 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P360 
