./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1315 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5097
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P781 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P645
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1242 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P742
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1483 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5381
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P366 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2505
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P791 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P879
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P381 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1824
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5604 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3568
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P429 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5534
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3329 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4985
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2722 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4120
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1936 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3124
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P586 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2008
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P661 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1886
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2798 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3765
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5035 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2830
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P927 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1441 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1308
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4046 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4525
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3936 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1274
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3925 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3435
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5343 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3857
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3571 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1976
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P232 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P591
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P449 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P264
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5966 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1933
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4081 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2447
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2695 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1204
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P162 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P676
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2684 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4611 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2818
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1036 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2818
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2568 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P180
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2369 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2697
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4544 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2188
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3106 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5395
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4983 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1067
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2595 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1181
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1807 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P902
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2549 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3420
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1985 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P348
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5273 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3346
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2321 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1269
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1831 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1098
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3451 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P242
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3610 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P47
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4434 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4728
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2347 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P617
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4391 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5407
./ti2 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2659 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1868
