./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2558 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2268 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P269 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5383 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5294 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P84 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1725 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P264 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3417 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3171 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3630 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3509 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4728 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P961 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5984 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1273 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2704 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P269 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3650 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1712 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P825 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P557 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P962 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1942 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P127 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5584 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1472 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P781 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5597 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1746 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1256 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P838 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2180 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1309 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2538 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5724 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1889 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3957 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3933 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1545 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P345 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/ontology-beta#claim /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P276 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1855 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P1584 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P592 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P233 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2284 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P968 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2002 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P442 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P949 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1997 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P863 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3265 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2174 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P480 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4839 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1981 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P683 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P691 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2959 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4659 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P950 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3987 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/ontology-beta#statementValueNormalized /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P123 /data/graphs/wikidata/sorted/rels/bfs-sorted/ontology-beta#claim 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P559 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3472 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2002 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4023 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P102 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1447 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2186 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2929 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2980 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5381 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1662 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5586 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2547 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3219 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5130 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2180 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1818 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3219 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4312 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P162 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P856 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3441 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3794 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P856 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2574 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1285 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3579 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5288 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1814 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P454 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3459 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P181 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5397 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3626 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1886 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3513 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P575 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P127 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1212 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5652 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4169 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P268 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5357 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P1795 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P241 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4643 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P1795 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1559 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P20 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2397 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1315 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2750 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1299 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2268 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P20 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1942 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2013 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3936 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3940 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P227 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2359 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3222 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4629 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2040 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4807 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1403 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1989 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2003 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P244 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5800 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P26 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P512 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1045 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2383 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4223 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1093 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2980 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P227 
./t3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1651 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P553 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P856 
