./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P197 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P800 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1366 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P206 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4839 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4132 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P461 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4342 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P141 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4746 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1313 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P541 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P736 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1040 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P648 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P750 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P98 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3984 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2302 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1366 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P461 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P61 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P547 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2435 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1855 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1444 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1389 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P747 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1462 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P780 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P682 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1056 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2293 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P509 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1256 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P647 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1923 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P505 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3912 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P159 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4854 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1687 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1963 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P227 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P127 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P451 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P428 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P509 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1376 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P36 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P608 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P269 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P200 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P248 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1424 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P398 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P183 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2572 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1990 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P101 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4746 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3450 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P463 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1661 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P344 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1056 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1552 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3602 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1423 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1308 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P914 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P155 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P910 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P669 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P915 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4244 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1387 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P461 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3916 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P511 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P101 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P902 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1950 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P460 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P495 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2239 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1629 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1709 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P206 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P138 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P4672 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P344 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P195 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P535 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P5280 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P156 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P487 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3781 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P186 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P508 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P163 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1629 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P227 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1709 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1366 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1365 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P184 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P25 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1615 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P264 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P725 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3136 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P688 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3781 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1748 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P655 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P175 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3040 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1414 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P553 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1661 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1313 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P460 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P935 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P870 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P828 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1417 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1830 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P750 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P166 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P36 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P301 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P69 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P3494 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1346 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2601 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1591 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P710 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P1015 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P1347 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P607 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-normalized-P1014 
./j3 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P530 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P205 /data/graphs/wikidata/sorted/rels/bfs-sorted/prop-direct-P2427 
